### ISSUE TITLE
It is not clear in readme that block command requires a plugin or theme be set.

### ISSUE THREAD

**Issue by Shelob9** [wp-cli/scaffold-command#104]
So first time user of the `wp scaffold block` and I got a little confused by the readme. I assumed it would just make a block for me where ever I ran it. It took me a minute to figure out that a block has to belong to a plugin or theme, which makes a lot of sense, not questioning that. Just saying the documentation confused me. PR incoming.

**Comment by danielbachhuber** [comment]
🔨
