### ISSUE TITLE
Define the textdomain correctly for block scaffold

### ISSUE THREAD

**Issue by grappler** [wp-cli/scaffold-command#123]
As mentioned in https://github.com/wp-cli/scaffold-command/pull/96/files#r164610714 the JS i18n functions do not except the second argument for the text domain. https://github.com/WordPress/gutenberg/blob/master/i18n/index.js#L42

There does not seem to be a way to define the text domain at the moment. https://github.com/WordPress/gutenberg/issues/4147

**Comment by gitlost** [comment]
Ta v much @grappler 

From https://github.com/wp-cli/wp-cli/issues/4512#issuecomment-361443041
> The temp solution today would be to remove the text domain. Once there is a correct way of adding the text domain that could be added in a future release...

Sounds good to me...

**Comment by schlessera** [comment]
This was already fixed in https://github.com/wp-cli/scaffold-command/commit/c74032f33bf31f90a8c664ac1498f2456ea98e74

**Comment by grappler** [comment]
Oh, I must be doing something wrong. After running `wp cli update --nightly` today. 
`WP-CLI 1.5.0-alpha-d790e72`

The command I ran `wp scaffold block pdf-block-2 --title="PDF Block 2" --plugin=pdf-block-2 --dashicon=media-document`

I get the following for `block.js`:

```php
( function( wp ) {
	var el = wp.element.createElement;
	var __ = wp.i18n.__;

	// Visit https://wordpress.org/gutenberg/handbook/block-api/ to learn about Block API
	wp.blocks.registerBlockType( 'pdf-block-2/pdf-block-2', {
		title: __( 'PDF Block 2', 'pdf-block-2' ),

		icon: 'media-document',

		category: 'widgets',

		// Remove to make block editable in HTML mode.
		supportHTML: false,

		edit: function( props ) {
			return el(
				'p',
				{ className: props.className },
				__( 'Replace with your content!', 'pdf-block-2' )
			);
		},

		save: function() {
			return el(
				'p',
				{},
				__( 'Replace with your content!', 'pdf-block-2' )
			);
		}
	} );
} )(
	window.wp
);
```

**Comment by schlessera** [comment]
@grappler Don't worry, we haven't pushed a release for the `scaffold` command that contains this change.

But when providing bug reports, you should always first check the latest state of the `master` branch, not the released packages: https://github.com/wp-cli/scaffold-command/blob/master/templates/block-block-js.mustache#L27

**Comment by grappler** [comment]
OH, I get it now. Sorry for the not so useful bug report.

Thanks again!

**Comment by schlessera** [comment]
No, thanks to you for bothering to submit one!
