### ISSUE TITLE
Scaffolding for theme unit tests does not work due to transient cache

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/scaffold-command#124]
The scaffolded theme unit test files do not successfully load the theme as the active theme. This is due to what appears to be a core bug in `register_theme_directory()`, but which can be fixed in the test bootstrap file.

When the theme test suite bootstrap file calls `register_theme_directory()`, an entry is added to the `$wp_theme_directories` global. When WordPress attempts to load the active theme, it ultimately calls `get_theme_roots()` which first checks for a cached value in the `theme_roots` transient. This transient gets populated before the `muplugins_loaded` hook fires, which means calling `register_theme_directory()` at this point has no effect because it does not flush the `theme_roots` transient.

This bug can be worked around by calling `delete_site_transient( 'theme_roots' )` after calling `register_theme_directory()` in the test suite bootstrap file.

Patch coming up.

Core issue: https://core.trac.wordpress.org/ticket/43228

**Comment by gitlost** [comment]
Ta, note there was a PR merged https://github.com/wp-cli/scaffold-command/pull/116 for 1.5.0 which may have addressed this already....

**Comment by johnbillion** [comment]
Oh thanks, I hadn't seen that! It looks like it probably fixes the same issue. I'll take a look and confirm.

**Comment by johnbillion** [comment]
Fixed in #116
