### ISSUE TITLE
wp scaffold block using --theme outputs the wrong code?

### ISSUE THREAD

**Issue by JakeImhoff** [wp-cli/scaffold-command#127]
Hello,

Today I tried using scaffold to create a block for gutenberg, I was using the --theme option. What me and my colleague found out is that the wp cli still implements plugin_url instead of something for the theme, and we have the following fix for it;

In code of the block e.g. 'blocks/my-custom-block.php'
Instead of:
`$dir = dirname( __FILE__ );`
Use:
`$dir = get_template_directory() . '/blocks';`

And instead of:
`plugins_url( $block_js, __FILE__ ),`
Use:
`get_template_directory_uri() . "/blocks/$block_js",`

The only thing you have to do next is go to your functions.php in the theme and paste this:
`require( get_template_directory() . '/blocks/my-custom-block.php' );`

I hope this helps some people out!

**Comment by danielbachhuber** [comment]
Thanks for the report, @JakeImhoff. This is a bug, in fact.
