### ISSUE TITLE
Add 'WooCommerce boilerplate' option to command "wp scaffold _s"

### ISSUE THREAD

**Issue by mburridge** [wp-cli/scaffold-command#139]
underscores.me has a checkbox option to 'sassify' the theme, and the "wp scaffold _s" command has a corresponding --sassify option.

underscores.me now has a checkbox option to add 'WooCommerce boilerplate'. Can this be added as a  command line option to "wp scaffold _s"?

**Comment by schlessera** [comment]
Yes, that makes sense to add it for consistency, provided the _s API lets us pass this through.

**Comment by schlessera** [comment]
The underscores-me API can be explored in the source code here: https://github.com/Automattic/underscores.me/blob/master/plugins/underscoresme-generator/underscoresme-generator.php

Adding an option should be as simple as adding a new argument to the command, and then mapping that command to the corresponding API option in the array that is passed to the request body.
