### ISSUE TITLE
Refactor circleci with aliases to reduce redundancy

### ISSUE THREAD

**Issue by JasonTheAdams** [wp-cli/scaffold-command#148]
Currently the default circleci configuration is pretty redundant as each version of PHP is a duplicate. This makes adding further versions even more duplicate code. There's a more concise way to do this in YAML using aliases.

I was going to make a PR for this, but saw that the guidelines request an issue be made first. That said, you can see the change to be merged here: https://github.com/JasonTheAdams/scaffold-command/blob/refactored-circleci-with-aliases/templates/plugin-circle.mustache

Using aliases, we reduce the total lines by 54. It also makes it nice and readable. I couldn't trim it down further as the PHP 5.6 job has unique testing. Still, I managed to reduce it a fair amount.

Please let me know what you think and if you'd like me to make a PR! 😄

**Comment by schlessera** [comment]
@JasonTheAdams Changes look good to me, I'm open to include these. Please submit your PR so we can review and merge.

**Comment by JasonTheAdams** [comment]
@schlessera PR is created. Feel free to close this if that's protocol.
