### ISSUE TITLE
Use the branch instead of the tag for the test suite checkout

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/scaffold-command#18]
In `install-wp-tests.sh` the `tags` directory of the core test suite is used. For example, calling `install-wp-tests.sh <name> <user> <pass> <host> 4.7` results in the `tags/4.7` directory of the test suite being checked out.

Ref: https://github.com/wp-cli/scaffold-command/blob/8015b662c232565d86962894618e38b5e5d43de1/templates/install-wp-tests.sh#L26-L27

The disadvantage of this is that any fixes which get made to the test infrastructure in branch point releases don't get picked up by the test install script. For example, specifying a WordPress version of 4.7 checks out the test suite for 4.7, but doesn't include the recent changes in 4.7.1 - 4.7.5.

In my User Switching plugin I changed `install-wp-tests.sh` so it uses the branch instead of the tag when a two-digit WordPress version number is specified.

```shell
if [[ $WP_VERSION =~ [0-9]+\.[0-9]+ ]]; then
	WP_TESTS_TAG="branches/$WP_VERSION"
elif [[ $WP_VERSION =~ [0-9]+\.[0-9]+\.[0-9]+ ]]; then
	WP_TESTS_TAG="tags/$WP_VERSION"
```

This means the test suite includes changes which have been backported to the 4.7 branch. The notable fix that was backported recently was support for PHPUnit 6+ which caused breakage all over the place.

Does it make sense to change the `install-wp-tests.sh` template to use this pattern?

**Comment by danielbachhuber** [comment]
> Does it make sense to change the `install-wp-tests.sh` template to use this pattern?

I'm amenable to this.

**Comment by desrosj** [comment]
This would be very helpful. We have many internal plugins that we need to update our Travis configurations for when point releases come out. Just saying `4.7`, `4.6` would save a bunch of time.
