### ISSUE TITLE
Scaffold generates nonworking Gutenberg block

### ISSUE THREAD

**Issue by Luke-SF** [wp-cli/scaffold-command#191]
Scaffold can create an invalid block that WP5.0 won't recognize.

```./wp-cli.phar scaffold block prayer-cloud --title="anytitle" --plugin=com.my.javastyle.pluginname```

Now, register_block_type calls the register in Wordpress' class-wp-block-type-registry.php and you can see it returns false because it doesn't match:

```$name_matcher = '/^[a-z0-9-]+\/[a-z0-9-]+$/';```

**Comment by schlessera** [comment]
Indeed, we should verify the block name and throw and error if it doesn't fit the requirements.

**Comment by Luke-SF** [comment]
Still happening with --plugin=something.with.dots

**Comment by swissspidy** [comment]
@Luke-SF We haven't made any changes to the scaffolding yet to validate errors, so yes, this is still happening. In the meantime, just don't use dots :-)

**Comment by schlessera** [comment]
Fixed via #203
