### ISSUE TITLE
wp scaffold block missing closing double quote

### ISSUE THREAD

**Issue by povedica** [wp-cli/scaffold-command#192]
There is a bug when running wp scaffold block command
**Steps to reproduce**
- Run: wp scaffold block gutenblock --title="GutenBlock" --theme 
- cd wp-content/themes/your-theme/blocks/
- open gutenblock.php
- See line 25 of php file:
```get_template_directory_uri() . "/blocks/$index_js, //Missing doublequote close```

**Comment by povedica** [comment]
WP-CLI version:	2.0.1
PHP version:	7.2.4
Shell:	/bin/bash
OS:	Darwin 16.7.0 Darwin Kernel Version 16.7.0

**Comment by schlessera** [comment]
This was fixed already in https://github.com/wp-cli/scaffold-command/commit/5e771ec9f490c40cb6b9bb156a5d76427981b3f3, but is not yet part of a stable release. It will go into the v2.1.0 release on December 18th. Until then, you can use the `nightly` version to scaffold the block instead.
