### ISSUE TITLE
`bitbucket` isn't a valid `--ci` value

### ISSUE THREAD

**Issue by henrywright** [wp-cli/scaffold-command#198]
I can't seem to generate a configuration file for Bitbucket Pipelines. 

```
$ wp scaffold plugin-tests my-plugin --ci=bitbucket
Error: Parameter errors: Invalid value specified for 'ci' (Choose a configuration file for a continuous integration provider.)
```

Yet I can generate a configuration file for the CircleCI provider.

```
$ wp scaffold plugin-tests my-plugin --ci=circle
Success: Created test files.
```
Does this indicate an issue with the `bitbucket` provider?

**Comment by mvhirsch** [comment]
Does this still apply?

Looking at the help generated by `wp scaffold plugin-tests --help` there is an option `--ci=bitbucket`. Maybe this issue is outdated?

**Comment by henrywright** [comment]
> Does this still apply?

I haven't tried but note I used the `--ci-bitbucket` option originally and got the error message posted above

**Comment by swissspidy** [comment]
I cannot reproduce this. The Bitbucket files are created as expected when using this option.
