### ISSUE TITLE
WP_VERSION=nightly jumps to next major after branching

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/scaffold-command#20]
Ref: https://github.com/wp-cli/core-command/issues/17

If the above gets implemented, the `install-wp-tests.sh` template should be updated in order to introduce a `WP_VERSION=beta` flag to support the same functionality in the scaffolding of the unit test suite.

**Comment by danielbachhuber** [comment]
Requires WP.org API implementation https://github.com/wp-cli/core-command/issues/17#issuecomment-347227534
