### ISSUE TITLE
Add missing script to plugins package.json

### ISSUE THREAD

**Issue by derweili** [wp-cli/scaffold-command#224]
The `wp scaffold plugin`command creates a `package.json` and a `Gruntfile.js`

The Gruntfile has two main tasks:

- A task to generate pot files from source code
- A task to create a `Readme.md` file from `Readme.txt``

Both are create tasks but you can't run them directly out of the box.

To run them you need to global install grunt or you need to add scripts to the package.json.

I would recommend to add following scripts to the `package.json`:
```
  "scripts" : {
    "start" : "grunt default" ,
    "readme" : "grunt readme",
    "i18n" : "grunt i18n"
  },
```
1. `start` This represents the default grunt task in Gruntfile.js
2. `readme` This script represents the Grunt Task for Readme.md generation
3. `i18n` This script represents the Grund Task for .pot generation

**Comment by schlessera** [comment]
Fixed via #225
