### ISSUE TITLE
Simplify test rigging creation (don't require skip-database-creation in install-wp-tests.sh)

### ISSUE THREAD

**Issue by tedsecretsource** [wp-cli/scaffold-command#228]
## Feature Request

- [x ] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

**Summary**

The plugin scaffolding includes a script to install a temporary version of WordPress and create a test database for automated testing. Since the temporary version of WordPress is stored in a temporary location where files are deleted by the system on a regular basis (`sys_get_temp_dir()`), I am often left with a database defined in the database but no WordPress files. I then have to run the `install-wp-tests.sh` script again. However, since skip-database-creation is the last parameter, I also have to specify the host and the version in order to pass true to skip-database-creation. I think that when you run this script, it should be assumed that you are installing, from scratch, the test rigging and it is assumed the database will be emptied.

**Preconditions**
- install-wp-tests.sh has been run and the test database has been created
- the WordPress files in /tmp have been deleted

**Steps to Reproduce**
1. run `./install-wp-tests.sh test_project_db homestead secret`

**Expected Result**
- The script executes with no error
- The existing database is dropped and recreated (emptied)

**Actual Result**
- The script errors with "mysqladmin: CREATE DATABASE failed; error: 'Can't create database 'testwhatever'; database exists'"

**Workaround**
- Manually drop the database or include the missing parameters (host and wp version) so you can pass TRUE to skip-database-creation

**Describe the solution you'd like**

Insert the following line just before the database creation on line 150:
`mysqladmin drop $DB_NAME -f --user="$DB_USER" --password="$DB_PASS"$EXTRA > /dev/null 2>&1`

I'd be happy to submit this as a pull request but the guidelines suggest I mention it here first, so I am :-)

**Comment by tomhoad** [comment]
> NOTE: This script can be run multiple times without errors

It clearly can't, it fails if run more than once

**Comment by tedsecretsource** [comment]
@tomhoad Where are you quoting that line from? I seem to recall seeing it but can't find it now.

**Comment by tomhoad** [comment]
It's in the handbook at https://make.wordpress.org/cli/handbook/plugin-unit-tests/

**Comment by tedsecretsource** [comment]
Cool. Thanks. FWIW, we've just merged a fix for this issue. I don't know what version it will end up in, but it's there :-)
