### ISSUE TITLE
MySQL TravisCI

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/scaffold-command#231]
https://docs.travis-ci.com/user/database-setup/#mysql

Could it be that TravisCI needs additional configuration to start MySQL?

**Comment by szepeviktor** [comment]
Please see the complicated matrix: https://github.com/spacedmonkey/echo-js-lazy-load/pull/11/files

**Comment by danielbachhuber** [comment]
We're going to remove Travis entirely https://github.com/wp-cli/scaffold-command/issues/253#issuecomment-1807870005
