### ISSUE TITLE
bin/install-wp-tests.sh: 26 Syntax error

### ISSUE THREAD

**Issue by endriu84** [wp-cli/scaffold-command#24]
Hello,
I got this error on every plugin i try to wrap with tests
I use:  wp scaffold plugin-tests some-plugin

and I'm getting error when I'm trying to run sh script:

bin/install-wp-tests.sh: 26: bin/install-wp-tests.sh: Syntax error: "(" unexpected (expecting "then")

lines from 26 to 30 looks like this
if [[ $WP_VERSION =~ [0-9]+\.[0-9]+(\.[0-9]+)? ]]; then
	WP_TESTS_TAG="tags/$WP_VERSION"
elif [[ $WP_VERSION == 'nightly' || $WP_VERSION == 'trunk' ]]; then
	WP_TESTS_TAG="trunk"
else

I'm on ubuntu 16.

**Comment by gitlost** [comment]
It's a `bash` script so needs to be run by `bash`, not `sh`.

**Comment by endriu84** [comment]
Thank You gitlost, It works with bash :)
