### ISSUE TITLE
Remove Travis CI from scaffolding options

### ISSUE THREAD

**Issue by lukecav** [wp-cli/scaffold-command#253]
Travis CI build config file should be updated to use Ubuntu Xenial 16.04.
`dist: trusty` should be changed to `dist: xenial`. Since Trusty is EOL by Canonical.
https://docs.travis-ci.com/user/reference/xenial/
https://docs.travis-ci.com/user/reference/trusty/

**Comment by swissspidy** [comment]
At this point we might want to consider just dropping the Travis CI config altogether

**Comment by danielbachhuber** [comment]
> At this point we might want to consider just dropping the Travis CI config altogether

👍
