### ISSUE TITLE
Tweak the `addtextdomain` grunt task config to replace instead of append textdomains

### ISSUE THREAD

**Issue by nikolov-tmw** [wp-cli/scaffold-command#27]
So, I just used `wp scaffold plugin` for the first time and I was very impressed :smiley: 

I took a look at the `addtextdomain` task and gave it a try. The result though was pretty confusing - I already had textdomains defined in most of my `i18n` functions and what I saw in the diff was that the textdomain of my plugin was just tacked onto the end of the `__()` call for instance.

I went on a search through the [cedaro/grunt-wp-i18n](https://github.com/cedaro/grunt-wp-i18n/) repository and found out that some time ago they added a configuration option that allows you to replace all textdomains with the one specified in the `addtextdomain.options.textdomain` config.

Is it just me or is it a bit pointless to have `addtextdomain` only append the textdomain instead of having it replace any existing textdomains? This technically means that unless you package your plugin separately and always keep your working copy without textdomains you can only run `grunt i18n` once, otherwise you'll end up with an ever growing list of textdomains.

So, I think it would make sense to adjust the auto-generated `Gruntfile.js` so that `addtextdomain.target` config is replaced with this: 

```
update_all_domains: {
	options: {
		updateDomains: true
	},
	src: [ '*.php', '**/*.php', '!node_modules/**', '!php-tests/**', '!bin/**' ]
}
```

**Comment by danielbachhuber** [comment]
> So, I just used `wp scaffold plugin` for the first time and I was very impressed 😃

Awesome!

> So, I think it would make sense to adjust the auto-generated `Gruntfile.js` so that `addtextdomain.target` config is replaced with this:

I'm amenable to this change. Want to submit a PR?
