### ISSUE TITLE
Update documentation to inform that WP-CLI isn't recommended to generate block scaffolding

### ISSUE THREAD

**Issue by Rahmon** [wp-cli/scaffold-command#272]
The section [Generate Blocks with WP-CLI ](https://developer.wordpress.org/block-editor/tutorials/block-tutorial/generate-blocks-with-wp-cli/) at Block Editor Handbook recommends do not use WP-CLI to generate block scaffolding. Instead, it's recommended to use the official script to generate a block: [@wordpress/create-block package](https://www.npmjs.com/package/@wordpress/create-block).

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @Rahmon. We did this with https://github.com/wp-cli/scaffold-command/pull/311
