### ISSUE TITLE
pull additional plugins in the WP test instance

### ISSUE THREAD

**Issue by drzraf** [wp-cli/scaffold-command#29]
When making integration tests one may need additional plugins.

Pasting here my _install-wp-tests-plugins.sh_

```
#!/usr/bin/env bash

if (( $# < 1 )); then
	echo "usage: $0 <plugin[:version]> [plugin[:version]]..."
	exit 1
fi

let force=0
WP_CORE_DIR=${WP_CORE_DIR-/tmp/wordpress/}

download() {
    if [ `which curl` ]; then
        curl -s "$1" > "$2";
    elif [ `which wget` ]; then
        wget -nv -O "$2" "$1"
    fi
}

set -ex

install_plugins() {

	if [ ! -d $WP_CORE_DIR ]; then
		return;
	fi
	for PLUGIN in "$@"; do
	    if [[ -d "$WP_CORE_DIR/wp-content/plugins/${PLUGIN%:*}" ]] && (( ! $force )); then
		continue;
	    fi
	    [[ $x =~ : ]] && VERSION="${PLUGIN##*:}"
	    FILENAME="${PLUGIN%:*}.${VERSION:-latest-stable}"
	    download "https://downloads.wordpress.org/plugin/$FILENAME.zip" "$WP_CORE_DIR/wp-content/plugins/$FILENAME.zip"
	    unzip -q "$WP_CORE_DIR/wp-content/plugins/$FILENAME.zip" -d "$WP_CORE_DIR/wp-content/plugins/"
	done
}

install_plugins "$@"
```

NB:
* I didn't implement `--force`
* There may exists better way to handle that feature (`wp-cli` itself, `composer.json`, ...)

**Comment by danielbachhuber** [comment]
Thanks for sharing, @drzraf. We'll leave this around here for a bit until we come to some decision on what to do with it.

It's worth noting that, even though this script _installs_ plugins, you'd still need to modify your `bootstrap.php` to load the plugins in your test suite.

**Comment by drzraf** [comment]
Indeed, there are not enabled. I'd rather left this to the test-writer.
Personally I'm using `setUp()`, eg:

```
public function setUp() {
        [...]
        include_once( ABSPATH . 'wp-admin/includes/plugin.php' );
        $result = activate_plugin( WP_CONTENT_DIR . '/plugins/advanced-custom-fields/acf.php', '', FALSE, FALSE );
        $this->assertNotWPError( $result );
        $result = activate_plugin( WP_CONTENT_DIR . '/plugins/contact-form-7/wp-contact-form-7.php', '', FALSE, FALSE );
        $this->assertNotWPError( $result );
        [...]
}

```

**Comment by wojsmol** [comment]
@danielbachhuber  This It would be useful as well as `wp plugin download`.

**Comment by drzraf** [comment]
no slack account. please copy/paste.
Actually I can't run my test without having ACF enabled. That's an automation must-have.
(the other one being the ability to smoothly but atomically export all stuff [inc. ACF])

**Comment by wojsmol** [comment]
@drzraf In my case I nead this for deploy script where theme and database is versioned in git. So now I nead install WP then install plugins and a the end import the database dump.

**Comment by drzraf** [comment]
I hope to never have to put database dumps in my Git repository in order to do testing but I concede it's still needed ATM.
I'm looking forward using WXR XML files since they are easily importable and quite "stable". They contain all the post's metas but they lack the semantic of each of them (= any plugin-related data, like ... ACF field definitions)

**Comment by danielbachhuber** [comment]
I think this particular use-case is outside the scope of what we should support automatically.
