### ISSUE TITLE
Use a prebuild Docker image for gitlab-ci.yml

### ISSUE THREAD

**Issue by drzraf** [wp-cli/scaffold-command#30]
The current gitlab-ci.yml file use the tetraweb/php on top of which it apt-get some stuff and then manually download WordPress core.

But having a prebuilt image would make builds much cheaper/quicker to request an image alredy containing all the needed stuff (zip, mysql, WordPress, ...). `chriszarate/wordpress` as an example.
It could even make most of `before_script` and `bin/install-wp-tests.sh` superfluous.
If no existing image fit the need, one `wordpress-test-image` repository + `Dockerfile` could be provided by wp-cli, built and provided by hub.docker.io.

**Comment by danielbachhuber** [comment]
> request an image alredy containing all the needed stuff (zip, mysql, WordPress, ...).

How would you handle testing against different versions of WordPress (and their corresponding test suites)?

> If no existing image fit the need, one `wordpress-test-image` repository + `Dockerfile` could be provided by wp-cli, built and provided by hub.docker.io.

What's the level of effort in building / maintaining this?

**Comment by drzraf** [comment]
About WordPress versions, it's more about avoiding long download/redownload time. Let's say a couple of mainstream WordPress versions are already bundled in the image, most users would have very quick test execution (those wanting some specific tags could still download it as a redundant job every time they commit)

About the level of effort, it's subjective. I think it's less work to create a custom and pleasant image for WordPress testers once for all rather than relying on a buggy, partial, unstable image.

**Comment by danielbachhuber** [comment]
@drzraf I'm open to changing the scaffolded `gitlab-ci.yml` file to a different Docker image. At the moment, WP-CLI has no plans to maintain its own Docker image.

**Comment by tianon** [comment]
@danielbachhuber if you're ever interested in contributing to, co-maintaining, or even taking over entirely [the `wordpress` image that's part of the Docker "official images" program](https://hub.docker.com/_/wordpress/) ([GitHub](https://github.com/docker-library/wordpress)), which includes a WP-CLI-based set of tags, we'd be thrilled to coordinate that :heart:

Thanks for your work!

**Comment by danielbachhuber** [comment]
Thanks for the offer, @tianon. I don't have much bandwidth to contribute at this point but I'd encourage you to check out the nascent [WordPress hosting community group](https://make.wordpress.org/hosting/). There may be some interest there, particularly as we collaborate around [hosting best practices documentation](https://github.com/ataylorme/WordPress-Hosting-Best-Practices-Documentation)
