### ISSUE TITLE
Scaffold plugin doesn't work due to missing ".editorconfig"

### ISSUE THREAD

**Issue by AdamReece-WebBox** [wp-cli/scaffold-command#309]
Hello,

The `scaffold plugin` command doesn't work. It always fails with error:

> Error: Couldn't find .editorconfig

We're using WP CLI 2.6.0.

**Comment by danielbachhuber** [comment]
Hey @AdamReece-WebBox,

Thanks for the report!

Were you able to figure this out? If not, can you share `wp cli info`?

**Comment by AdamReece-WebBox** [comment]
Hi Daniel,

Thanks for your response.

I believe this issue was caused by a client's website using the Buddy Boss platform. Whilst we've not gotten into why exactly, as the inclusion of that platform was not our choice, simply including `--skip-plugins=buddyboss-platform` to my command appeared to work around this.

To be honest the project in question is a bit of a mess inherited via multiple different agencies. We've definitely since got our own custom command registered and working though, despite the torrents of unrelated warnings specific to this client project.

**Comment by danielbachhuber** [comment]
Thanks for the additional details, @AdamReece-WebBox.

Glad you were able to find a workaround 😄  If you're able to track down more specific reproduction steps in the future, please let us know!

**Comment by ABCdatos** [comment]
Hope this helps to clarify something:

My notes (translated) have a historical mention to this error, this is from years ago:

```
# cd comand is required to avoid an error:
# Error: Couldn't find .editorconfig
cd /var/www/mysite.com/web
```
And the comand I use (with some user/site data changed), calling it as root:

`sudo -E -u webuser /usr/local/bin/wp --path="/var/www/mysite.com/web" scaffold child-theme twentytwentythree-child --parent_theme=twentytwentythree --theme_name="Twenty Twenty-Three Child" --author=Me --author_uri=https://mysite.com --activate`

Yesterday I forgot to issue the cd comand first and the error appears again.

Regards!
