### ISSUE TITLE
don't make WP bootstrap so phpunit-centric

### ISSUE THREAD

**Issue by drzraf** [wp-cli/scaffold-command#32]
Following up #31 I intend to use `behat` on a fully initialized and boostrapable WordPress instance.
For this to work the current bootstrap scripts are too phpunit-centric:
[ ] they rely upon phpunit presence (being run by phpunit)
[ ] they rely upon hardcoded value for host/port/... (issue with wp-config initialization)
[ ] they rely upon *not* calling `wp()`

Could we discuss this topic here?

**Comment by danielbachhuber** [comment]
`install-wp-tests.sh` is specifically for installing the WordPress PHPUnit test suite against a plugin (or theme). Acting as a generic test suite installer is out of scope for `wp scaffold plugin-tests`.

You're welcome to create your own standalone command: https://make.wordpress.org/cli/handbook/commands-cookbook/

For information on how commands become officially maintained, see: https://github.com/wp-cli/ideas/blob/master/README.md

**Comment by drzraf** [comment]
I want to test a WP plugin using a WP instance, thus `wp scaffold plugin-tests` seems like a good fit for a new command name.
(phpunit is not the only way to do WP plugin testing)
