### ISSUE TITLE
Make methods to scaffold things more accessible

### ISSUE THREAD

**Issue by benjamingrolleau** [wp-cli/scaffold-command#327]
I was working on a custom command to scaffold my own files. I tried to extend `Scaffold_Command`, but as mentioned in #3957, I have to rewrite some methods because their parent versions are private.

For example : `canonicalize_path`, `check_target_directory`.

I think it would be nice to make these methods protected, so we can extend `Scaffold_Command` easier.

**Comment by danielbachhuber** [comment]
Thanks for the suggestion! Replied here: https://github.com/wp-cli/scaffold-command/pull/328#issuecomment-1917876048
