### ISSUE TITLE
Test scaffolding: PHPUnit 4.8 installed for PHP nightly on travis

### ISSUE THREAD

**Issue by ssnepenthe** [wp-cli/scaffold-command#4]
PHP nightly on travis is version 7.2 but the TRAVIS_PHP_VERSION var is still set to 'nightly' so:

```
if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
        composer global require "phpunit/phpunit=5.7.*"
      else
        composer global require "phpunit/phpunit=4.8.*"
fi
```

results in the installation of 4.8.*.

Bash is foreign to me but I assume it should be possible to throw a secondary condition in there to also check for "nightly"?

**Comment by ssnepenthe** [comment]
Or alternatively reverse the condition so that PHPUnit 5.7.* is the default unless we are on PHP5?

```
if [[ ${TRAVIS_PHP_VERSION:0:2} == "5." ]]; then
        composer global require "phpunit/phpunit=4.8.*"
      else
        composer global require "phpunit/phpunit=5.7.*"
fi
```

**Comment by danielbachhuber** [comment]
> Or alternatively reverse the condition so that PHPUnit 5.7.* is the default unless we are on PHP5?

Reversing the condition seems like a fine approach to me.
