### ISSUE TITLE
Call to `bash templates/install-wp-tests.sh` doesn't work in nightly automated tests

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/scaffold-command#41]
![image](https://user-images.githubusercontent.com/36432/29579893-0d51ee64-8729-11e7-8dc0-176fba843167.png)

From https://travis-ci.org/wp-cli/automated-tests/jobs/267261114

Introduced in #37 but it was only revealed now because [I tagged a release](https://github.com/wp-cli/scaffold-command/releases/tag/v1.0.6).

**Comment by danielbachhuber** [comment]
@miya0001 I _believe_ the `templates/install-wp-tests.sh` file is present but located on a different path.

It may be easier to call `wp scaffold plugin`, and then use the `bin/install-wp-tests.sh` generated by the WP-CLI command.

**Comment by miya0001** [comment]
Oh... Do you fix it? I can do it tomorrow.

**Comment by danielbachhuber** [comment]
@miya0001 You can have the first pass at it if you prefer. I assigned the issue to myself so it stays on my radar and I make sure it's fixed up this week.

**Comment by miya0001** [comment]
Thanks, I will fix it. :muscle:
