### ISSUE TITLE
`pluralize()` isn't working perfectly

### ISSUE THREAD

**Issue by miya0001** [wp-cli/scaffold-command#48]
`pluralize()` isn't working perfectly, please see discussion on #44.
Should we add `doctrine/inflector` to composer dependencies and improve implementation of the `pluralize()`?

Related: #42  #44 #45

**Comment by danielbachhuber** [comment]
> Should we add doctrine/inflector to composer dependencies

It has a PHP 7.1 dependency: https://github.com/doctrine/inflector/blob/master/composer.json#L16

**Comment by miya0001** [comment]
Oh, we have to find another solution.

cc: @gitlost

**Comment by gitlost** [comment]
Ha, yeah, and I see they blogged about it last month http://www.doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html - and just sucked about 99% of the goodness out of the library.

We could just use the v1.1.0 release which doesn't have this silliness, or (my preference) just go old skool and copy the class file over, rename it `Doctrine_Inflector` and require it.

**Comment by danielbachhuber** [comment]
> (my preference) just go old skool and copy the class file over, rename it `Doctrine_Inflector` and require it.

Internalizing the class makes more sense to me too.

**Comment by miya0001** [comment]
> rename it Doctrine_Inflector and require it.

I agree too.
Is it to be `good-first-issues`?

**Comment by gitlost** [comment]
> Is it to be good-first-issues?

I think so...

**Comment by Umangvaghela** [comment]
@miya001 

Below solution is not perfect .. need to check properly, because I use this in ROR. And it is my issue..

**Comment by miya0001** [comment]
`good-first-issues` is assigned to this issue.
It means that this issue is keeping for newer contributors.
Feel free to try this issue.

Thanks! 😄

**Comment by Umangvaghela** [comment]
@miya0001 

Not  in.....

Thanks 👍

**Comment by Umangvaghela** [comment]
@gitlost  @miya0001 

Your solution  good but more flexible  way available in another framework where pluralization define perfectly.Try to find and make it more secure pluralization.

Thanks

**Comment by danielbachhuber** [comment]
Landed in #54
