### ISSUE TITLE
Add PHPCompatibility sniffs to scaffolded Codesniffer configuration

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/scaffold-command#60]
To help plugin and theme authors detect PHP version compatibility issues in their codebase, it would be helpful to add the [PHPCompatibility](https://github.com/wimg/PHPCompatibility) sniffs.

**Comment by GaryJones** [comment]
The relevant bit to add to `templates/phpcs.xml.dist` would be:

```xml
<rule ref="PHPCompatibility"/>
<config name="testVersion" value="5.3-"/>
```

...which says to check for all versions from 5.3 upwards (no upper limit of PHP version).

This seems like a sensible starting point for the lower bound, unless elsewhere in the scaffolding files presumes a different lower bound?

**Comment by jrfnl** [comment]
It would also be helpful to include a standard set of exclusions for things WP backfills.
See: https://github.com/wimg/PHPCompatibility/issues/514#issuecomment-340369984 for an example.

**Comment by stevegrunwell** [comment]
If we're adding PHP Compatibility checks to the phpcs.xml.dist file, would it make sense to [add a matching "Requires PHP" header](https://make.wordpress.org/plugins/2017/08/29/minimum-php-version-requirement/) to the generated plugin file?

Also, a big +1 for setting PHP 5.3 as the default minimum. I'd be happier with PHP 5.6+, but baby steps 😀

**Comment by jrfnl** [comment]
FYI: since my previous comment, a WP specific ruleset is now available from within the PHPCompatibility library, so you can just pull that in to use within your `phpcs.xml.dist` file: https://github.com/wimg/PHPCompatibility#using-a-frameworkcms-specific-ruleset
