### ISSUE TITLE
Add 'p' arg to show PHPCS progress

### ISSUE THREAD

**Issue by GaryJones** [wp-cli/scaffold-command#62]
Adding the `p` argument to `phpcs.xml.dist` allows progress to be shown when invoking `phpcs`, which gives confidence to the user that something is happening.

Change:
```xml
	<!-- Show sniff codes in all reports -->
	<arg value="s"/>
```

to:

```xml
	<!-- Show progress and sniff codes in all reports -->
	<arg value="ps"/>
```

**Comment by danielbachhuber** [comment]
👍
