### ISSUE TITLE
Missing files when running wp scaffold plugin-tests

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/scaffold-command#65]
Running `wp scaffold plugin-tests <plugin>` results in the `tests/includes` directory completely missing completely from the plugin. This causes the test suite to silently exit due to missing required files.

**Comment by danielbachhuber** [comment]
> results in the `tests/includes` directory completely missing completely from the plugin.

`wp scaffold plugin-tests` doesn't create a `tests/includes` directory?

**Comment by johnbillion** [comment]
🙃
