### ISSUE TITLE
Travis: allow Composer to determine appropriate PHPUnit version

### ISSUE THREAD

**Issue by ssnepenthe** [wp-cli/scaffold-command#74]
Any thoughts on allowing Composer to decide on PHPUnit version instead of manually inspecting TRAVIS_PHP_VERSION?

Instead of this:

https://github.com/wp-cli/scaffold-command/blob/382bcfff85c860e37321fd9e8019f30130ddedcc/templates/plugin-travis.mustache#L45-L49

You could do something like this:

```
composer global require "phpunit/phpunit=4.8.*|5.7.*"
```

Which would give us PHPUnit 5.7 instead of 4.8 when running PHP 5.6.

**Comment by danielbachhuber** [comment]
Seems reasonable.

This originated in https://github.com/wp-cli/wp-cli/pull/3463#commitcomment-20568441
