### ISSUE TITLE
.gitignore standard phpcs and phpunit configs?

### ISSUE THREAD

**Issue by ssnepenthe** [wp-cli/scaffold-command#79]
Something I noticed while checking the history for #77...

The reason for the `.xml.dist` extension for the phpunit config (per da9167d1d4b49cf5cb9d83f4e45d4bfa1ebc57d1, presumably holds for phpcs as well):

> Naming the file `phpunit.xml.dist` instead of `phpunit.xml` is considered a best practice because it allows other developers working on a project to override the configuration without messing with extra command line parameters or dirtying their local version control state.
> 
> See http://www.testically.org/2010/08/24/best-practice-how-to-ship-phpunit-configuration/

First, that linked site no longer appears to be active - here is an archived copy: http://web.archive.org/web/20160317185523/http://www.testically.org:80/2010/08/24/best-practice-how-to-ship-phpunit-configuration/

Second (and the point of this issue), part of the recommendation from that post is to add `phpunit.xml` to `.gitignore` to keep git status clean/prevent it from being accidentally committed.

So would it be beneficial for the standard configs to be added to the `plugin-gitignore.mustache` template?

**Comment by danielbachhuber** [comment]
> So would it be beneficial for the standard configs to be added to the `plugin-gitignore.mustache` template?

Yes, we can do this.
