### ISSUE TITLE
Add an explicitly output error message to the test bootstrap file

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/scaffold-command#89]
Previously: #55

If the server's `display_errors` directive is set to `Off` and the user tries to run their unit tests without first running `bash bin/install-wp-tests.sh ...`, they'll be greeted with blank output.

The uncaught exception is good if you have access to the error logs, or think to look there, but an error message which is explicitly output (via `echo`) would be even better.

**Comment by johnbillion** [comment]
Recommendation for the bootstrap template:

```php
if ( ! file_exists( $_tests_dir . '/includes/functions.php' ) ) {
	echo "Could not find $_tests_dir/includes/functions.php, have you run bin/install-wp-tests.sh ?";
	exit( 1 );
}
```

**Comment by danielbachhuber** [comment]
👍
